sherlock:
  build: .
  links:
    - etcd:etcd
    - redis:redis
    - memcached:memcached
  volumes:
    - .:/sherlock:Z
  entrypoint: coverage run --source=sherlock setup.py test
  stdin_open: true
  tty: true
etcd:
  image: vaidik/etcd
  command: |
    etcd --listen-client-urls="http://0.0.0.0:2379,http://0.0.0.0:4001" --advertise-client-urls="http://0.0.0.0:2379,http://0.0.0.0:4001"
  ports:
    - 2379:2379
    - 4001:4001
redis:
  image: redis
memcached:
  image: memcached
