name: CI/CD

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Instal Sherlock
        run: pip install -e .

      - uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: "sherlock tests"
          use-pylint: false
          use-pycodestyle: true
          use-flake8: true
          use-black: true
          use-mypy: true
          use-isort: true

  test:
    name: Test ${{ matrix.py }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest

    strategy:
      fail-fast: false
      matrix:
        os:
          - Ubuntu
        py:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"

    env:
      REDIS_HOST: 127.0.0.1
      ETCD_HOST: 127.0.0.1
      MEMCACHED_HOST: 127.0.0.1

    steps:
      - uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python ${{ matrix.py }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}
          cache: 'poetry'

      - name: Install `libmemcached-dev`
        run: sudo apt-get install -y libmemcached-dev

      - name: Install sherlock
        run: poetry install --all-extras

      - name: Run tests
        run: poetry run tox

      - uses: codecov/codecov-action@v3
