name: CI/CD

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install `uv`
        uses: astral-sh/setup-uv@v7.1.6
        with:
          enable-cache: true

      - name: Install linting tools
        run: uv sync --only-dev

      - name: Run Black
        run: uv run black --check sherlock tests

      - name: Run iSort
        run: uv run isort --check sherlock tests

      - name: Run flake8
        run: uv run flake8 sherlock tests

      - name: Run pycodestyle
        run: uv run pycodestyle sherlock tests

  test:
    name: Test ${{ matrix.py }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest

    strategy:
      fail-fast: false
      matrix:
        os:
          - Ubuntu
        py:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"

    env:
      REDIS_HOST: 127.0.0.1
      ETCD_HOST: 127.0.0.1
      MEMCACHED_HOST: 127.0.0.1

    steps:
      - uses: actions/checkout@v6

      - name: Install `uv`
        uses: astral-sh/setup-uv@v7.1.6
        with:
          enable-cache: true

      - name: Install `libmemcached-dev`
        run: sudo apt-get install -y libmemcached-dev

      - name: Install sherlock
        run: uv sync --all-extras

      - name: Run tests
        run: uv run tox

      - uses: codecov/codecov-action@v3
